/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    leads: Lead;
    products: Product;
    cultures: Culture;
    articles: Article;
    'posts-us': PostsUs;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    leads: LeadsSelect<false> | LeadsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    cultures: CulturesSelect<false> | CulturesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'posts-us': PostsUsSelect<false> | PostsUsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('pt-BR' | 'en' | 'es') | ('pt-BR' | 'en' | 'es')[];
  globals: {
    destaques: Destaque;
    settings: Setting;
    'settings-us': SettingsUs;
  };
  globalsSelect: {
    destaques: DestaquesSelect<false> | DestaquesSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'settings-us': SettingsUsSelect<false> | SettingsUsSelect<true>;
  };
  locale: 'pt-BR' | 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Contatos que chegaram pelos sites. Mude o status conforme o atendimento avança.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  status: 'novo' | 'em-contato' | 'qualificado' | 'convertido' | 'descartado';
  responsavel?: (number | null) | User;
  site: 'br' | 'us';
  formulario?: ('whatsapp' | 'contato' | 'trial' | 'trial-compact') | null;
  duplicadoDe?: (number | null) | Lead;
  nome: string;
  empresa?: string | null;
  email?: string | null;
  /**
   * Só dígitos, com DDI/DDD quando informado.
   */
  telefone?: string | null;
  mensagem?: string | null;
  /**
   * De onde veio o interesse: a página em que o contato clicou.
   */
  contexto?: {
    produto?: string | null;
    cultura?: string | null;
    detalhe?: string | null;
  };
  dados?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notas?:
    | {
        texto: string;
        autor?: (number | null) | User;
        data?: string | null;
        id?: string | null;
      }[]
    | null;
  pagina?: string | null;
  locale?: string | null;
  variante?: string | null;
  /**
   * Último toque antes do contato. O primeiro toque fica no JSON abaixo.
   */
  rastreamento?: {
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmTerm?: string | null;
    utmContent?: string | null;
    gclid?: string | null;
    fbclid?: string | null;
    referrer?: string | null;
    landing?: string | null;
    primeiroToque?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  dispositivo?: {
    tipo?: string | null;
    navegador?: string | null;
  };
  geo?: {
    pais?: string | null;
    regiao?: string | null;
    cidade?: string | null;
  };
  consentimento?: {
    texto?: string | null;
    data?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nome?: string | null;
  /**
   * Admin: tudo. Editor: conteúdo do Brasil. Comercial: trabalha os leads.
   */
  papel: 'admin' | 'editor' | 'comercial';
  /**
   * Sites cujos leads e conteúdos este usuário enxerga.
   */
  sites: ('br' | 'us')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Produtos do site Brasil. Textos em cada idioma pelo seletor "Idioma" no topo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Endereço: /produtos/<slug>.
   */
  slug: string;
  /**
   * Filtro do catálogo.
   */
  categoria: 'cat-tratamento' | 'cat-nutricao' | 'cat-protecao' | 'cat-aplicacao' | 'cat-manejo';
  culturasFiltro?:
    | (
        | 'cul-soja'
        | 'cul-milho'
        | 'cul-cafe'
        | 'cul-cana'
        | 'cul-algodao'
        | 'cul-feijao'
        | 'cul-citros'
        | 'cul-tomate'
        | 'cul-batata'
        | 'cul-pastagem'
      )[]
    | null;
  embalagens?: ('1L' | '10L' | '20L')[] | null;
  /**
   * Pílulas e destaques da página. Formato #RRGGBB.
   */
  corRotulo: string;
  /**
   * Vazio = cor do rótulo.
   */
  corCard?: string | null;
  /**
   * Menor aparece primeiro no catálogo.
   */
  ordem?: number | null;
  nome: string;
  /**
   * Pílula acima do nome. Ex.: Nutrição e Fisiologia Vegetal
   */
  tag?: string | null;
  descricao?: string | null;
  /**
   * Imagem quadrada com fundo transparente ou claro.
   */
  frasco?: (number | null) | Media;
  /**
   * Uma por linha.
   */
  culturasRotulo?: string | null;
  /**
   * Use quando o rótulo autoriza a cultura só em foliar ou só em TS. Substitui a lista acima.
   */
  gruposCulturas?:
    | {
        rotulo?: string | null;
        /**
         * Uma por linha.
         */
        culturas?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex.: adjuvante dosado por volume de calda. Substitui a lista de culturas.
   */
  notaCulturas?: string | null;
  problemas?:
    | {
        icone: 'seed' | 'sun' | 'drop' | 'leaf' | 'shield' | 'chart';
        titulo?: string | null;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  listaBeneficios?:
    | {
        titulo?: string | null;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Texto literal do rótulo. Uma tabela por forma de aplicação.
   */
  aplicacoes?:
    | {
        rotulo?: string | null;
        nota?: string | null;
        linhas?:
          | {
              cultura?: string | null;
              quando?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  notaAplicacoes?: string | null;
  /**
   * Todo número precisa vir com a fonte do ensaio na descrição.
   */
  listaResultados?:
    | {
        /**
         * Ex.: +13,4
         */
        valor?: string | null;
        /**
         * Ex.: sc/ha
         */
        unidade?: string | null;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Quatro fotos: a 1ª fica grande e a 4ª larga.
   */
  galeria?: (number | Media)[] | null;
  relacionados?:
    | {
        produto: number | Product;
        tag?: string | null;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  tagCatalogo?: string | null;
  resumoCatalogo?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Imagens e arquivos usados pelos sites. O texto alternativo é obrigatório.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * O que a imagem mostra, em uma frase. Lido por leitores de tela e pelo Google. Ex.: "Lavoura de soja no estádio R1".
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Culturas do site Brasil. Textos em cada idioma pelo seletor "Idioma" no topo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cultures".
 */
export interface Culture {
  id: number;
  /**
   * Endereço: /culturas/<slug>.
   */
  slug: string;
  /**
   * Menor aparece primeiro na grade e na home.
   */
  ordem?: number | null;
  nome: string;
  /**
   * Pílula acima do nome. Ex.: Grão
   */
  etiqueta?: string | null;
  descricao?: string | null;
  /**
   * Foto de campo usada no topo, na grade e na home.
   */
  foto?: (number | null) | Media;
  /**
   * Um item por linha.
   */
  listaAtuacao?: string | null;
  listaDesafios?:
    | {
        /**
         * Ex.: 01 · Tratamento de sementes
         */
        etapa?: string | null;
        titulo?: string | null;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Texto do folheto de sugestões de nutrição da cultura.
   */
  fasesManejo?:
    | {
        /**
         * Ex.: Fase 01
         */
        rotulo?: string | null;
        /**
         * Ex.: Tratamento de sementes ou V2
         */
        fase?: string | null;
        itens?:
          | {
              /**
               * Nome livre: vale também para produtos sem página no site.
               */
              produto?: string | null;
              dose?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  notaManejo?: string | null;
  /**
   * Ex.: Folheto Juma-Agro · Sugestões de nutrição para soja (2025)
   */
  fonte?: string | null;
  /**
   * Nome, cor e foto vêm do cadastro do produto.
   */
  recomendados?:
    | {
        produto: number | Product;
        tag?: string | null;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  preposicoes?: {
    /**
     * na / no / nos
     */
    em?: string | null;
    /**
     * da / do / dos
     */
    de?: string | null;
    /**
     * para a / para o
     */
    para?: string | null;
    /**
     * na sua / no seu
     */
    sua?: string | null;
  };
  aparencia?: {
    gradienteHero?: string | null;
    fundoHome?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Matérias do blog do site Brasil. Edite em cada idioma pelo seletor "Idioma" no topo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Endereço: /materias/<slug>. Só letras minúsculas, números e hífen.
   */
  slug: string;
  categoria: 'manejo' | 'nutricao' | 'pecuaria' | 'pesquisa' | 'sustentabilidade';
  data: string;
  /**
   * A mais recente marcada aparece no bloco grande do topo.
   */
  destaque?: boolean | null;
  /**
   * A home mostra as 3 mais recentes marcadas.
   */
  destaqueHome?: boolean | null;
  /**
   * Calculado pelo texto. Marque a opção abaixo para definir à mão.
   */
  tempoLeitura?: number | null;
  tempoLeituraManual?: boolean | null;
  titulo: string;
  /**
   * Aparece abaixo do título e como descrição no Google.
   */
  subtitulo?: string | null;
  capa: number | Media;
  /**
   * Aparece enquanto a foto carrega.
   */
  cor?:
    | (
        | 'from-green-700 to-emerald-950'
        | 'from-green-600 to-green-800'
        | 'from-teal-600 to-emerald-800'
        | 'from-amber-600 to-orange-800'
        | 'from-blue-600 to-indigo-800'
        | 'from-purple-600 to-purple-900'
      )
    | null;
  /**
   * Como aparece na matéria. Ex.: Eng. Agrônomo Marcos Silva
   */
  assinatura?: string | null;
  introducao?: string | null;
  secoes?:
    | {
        titulo?: string | null;
        /**
         * Deixe uma linha em branco entre os parágrafos.
         */
        paragrafos: string;
        id?: string | null;
      }[]
    | null;
  citacao?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Posts do blog do site americano, em inglês. Descreva o que o produto entrega, nunca o efeito na planta ou no inseto (FIFRA), e todo número com fonte.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts-us".
 */
export interface PostsUs {
  id: number;
  title: string;
  /**
   * One or two sentences. Shows on the blog list, on Google and when the link is shared.
   */
  excerpt?: string | null;
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bodyHtml?: string | null;
  /**
   * Ex.: foliar-feeding-in-florida. Vira /blog/endereço.
   */
  slug: string;
  date: string;
  author?: string | null;
  category?: ('field-notes' | 'crop-nutrition' | 'trials' | 'company') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'cultures';
        value: number | Culture;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'posts-us';
        value: number | PostsUs;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  status?: T;
  responsavel?: T;
  site?: T;
  formulario?: T;
  duplicadoDe?: T;
  nome?: T;
  empresa?: T;
  email?: T;
  telefone?: T;
  mensagem?: T;
  contexto?:
    | T
    | {
        produto?: T;
        cultura?: T;
        detalhe?: T;
      };
  dados?: T;
  notas?:
    | T
    | {
        texto?: T;
        autor?: T;
        data?: T;
        id?: T;
      };
  pagina?: T;
  locale?: T;
  variante?: T;
  rastreamento?:
    | T
    | {
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
        utmContent?: T;
        gclid?: T;
        fbclid?: T;
        referrer?: T;
        landing?: T;
        primeiroToque?: T;
      };
  dispositivo?:
    | T
    | {
        tipo?: T;
        navegador?: T;
      };
  geo?:
    | T
    | {
        pais?: T;
        regiao?: T;
        cidade?: T;
      };
  consentimento?:
    | T
    | {
        texto?: T;
        data?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  categoria?: T;
  culturasFiltro?: T;
  embalagens?: T;
  corRotulo?: T;
  corCard?: T;
  ordem?: T;
  nome?: T;
  tag?: T;
  descricao?: T;
  frasco?: T;
  culturasRotulo?: T;
  gruposCulturas?:
    | T
    | {
        rotulo?: T;
        culturas?: T;
        id?: T;
      };
  notaCulturas?: T;
  problemas?:
    | T
    | {
        icone?: T;
        titulo?: T;
        descricao?: T;
        id?: T;
      };
  listaBeneficios?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        id?: T;
      };
  aplicacoes?:
    | T
    | {
        rotulo?: T;
        nota?: T;
        linhas?:
          | T
          | {
              cultura?: T;
              quando?: T;
              id?: T;
            };
        id?: T;
      };
  notaAplicacoes?: T;
  listaResultados?:
    | T
    | {
        valor?: T;
        unidade?: T;
        descricao?: T;
        id?: T;
      };
  galeria?: T;
  relacionados?:
    | T
    | {
        produto?: T;
        tag?: T;
        descricao?: T;
        id?: T;
      };
  tagCatalogo?: T;
  resumoCatalogo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cultures_select".
 */
export interface CulturesSelect<T extends boolean = true> {
  slug?: T;
  ordem?: T;
  nome?: T;
  etiqueta?: T;
  descricao?: T;
  foto?: T;
  listaAtuacao?: T;
  listaDesafios?:
    | T
    | {
        etapa?: T;
        titulo?: T;
        descricao?: T;
        id?: T;
      };
  fasesManejo?:
    | T
    | {
        rotulo?: T;
        fase?: T;
        itens?:
          | T
          | {
              produto?: T;
              dose?: T;
              id?: T;
            };
        id?: T;
      };
  notaManejo?: T;
  fonte?: T;
  recomendados?:
    | T
    | {
        produto?: T;
        tag?: T;
        descricao?: T;
        id?: T;
      };
  preposicoes?:
    | T
    | {
        em?: T;
        de?: T;
        para?: T;
        sua?: T;
      };
  aparencia?:
    | T
    | {
        gradienteHero?: T;
        fundoHome?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  slug?: T;
  categoria?: T;
  data?: T;
  destaque?: T;
  destaqueHome?: T;
  tempoLeitura?: T;
  tempoLeituraManual?: T;
  titulo?: T;
  subtitulo?: T;
  capa?: T;
  cor?: T;
  assinatura?: T;
  introducao?: T;
  secoes?:
    | T
    | {
        titulo?: T;
        paragrafos?: T;
        id?: T;
      };
  citacao?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts-us_select".
 */
export interface PostsUsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  body?: T;
  bodyHtml?: T;
  slug?: T;
  date?: T;
  author?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nome?: T;
  papel?: T;
  sites?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Produtos da seção colorida da home, na ordem em que aparecem. O Aminosan abre sempre a seção; os demais você adiciona, tira e reordena arrastando.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destaques".
 */
export interface Destaque {
  id: number;
  /**
   * Não sai nem muda de posição: a animação da seção anterior termina no frasco dele. Aqui ficam só os textos.
   */
  aminosan?: {
    descricao?: string | null;
    /**
     * Os 3 pontos à direita do frasco. Vazio usa o texto atual do site.
     */
    beneficios?:
      | {
          icone:
            | 'recovery'
            | 'leaf'
            | 'bloom'
            | 'sprout'
            | 'roots'
            | 'shield'
            | 'bug'
            | 'molecule'
            | 'award'
            | 'energy'
            | 'metabolism';
          titulo: string;
          apoio?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Mínimo 2 para o carrossel funcionar. Arraste para mudar a ordem; clique no produto para abrir.
   */
  produtos?:
    | {
        /**
         * Nome, frasco, embalagens e link vêm do cadastro do produto.
         */
        produto: number | Product;
        /**
         * Para quebrar nomes longos: uma linha por parte, ex.: "Acorda" e "Ultra". Vazio usa o nome do produto.
         */
        titulo?: string | null;
        descricao: string;
        /**
         * Os 3 pontos à direita do frasco.
         */
        beneficios?:
          | {
              icone:
                | 'recovery'
                | 'leaf'
                | 'bloom'
                | 'sprout'
                | 'roots'
                | 'shield'
                | 'bug'
                | 'molecule'
                | 'award'
                | 'energy'
                | 'metabolism';
              titulo: string;
              apoio?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Escura: o texto é branco. Ex.: #062418.
         */
        corFundo: string;
        /**
         * Anéis, ícones e embalagens. Ex.: #f2c94c.
         */
        corDestaque: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contato, endereços e redes que aparecem no site Brasil. Ao salvar, o site atualiza em alguns segundos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Com DDI e DDD, como deve aparecer: +55 19 99964-8186. Todos os botões de WhatsApp usam este número.
   */
  whatsapp?: string | null;
  /**
   * Como deve aparecer: (19) 3891-6415.
   */
  telefone?: string | null;
  email?: string | null;
  emailCompras?: string | null;
  emailRH?: string | null;
  /**
   * Uma linha por período, ex.: "Seg a qui, 7h30 às 17h15" e "Sex, 7h30 às 16h". Vazio: usa o texto padrão do site.
   */
  horario?: string | null;
  enderecoBR?: {
    empresa?: string | null;
    /**
     * Uma linha por quebra.
     */
    linhas?: string | null;
  };
  enderecoUS?: {
    empresa?: string | null;
    /**
     * Uma linha por quebra.
     */
    linhas?: string | null;
  };
  /**
   * O que o Google Maps procura no mapa da página de contato.
   */
  mapa?: string | null;
  /**
   * Link completo do perfil. A rede sem link some do rodapé.
   */
  redes?: {
    instagram?: string | null;
    tiktok?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
    facebook?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contato, endereço e redes que aparecem no site dos EUA. Campo vazio não aparece no site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-us".
 */
export interface SettingsUs {
  id: number;
  /**
   * Ex.: sales@juma-agro.com
   */
  email?: string | null;
  /**
   * Como deve aparecer: +1 (863) 555-0100.
   */
  phone?: string | null;
  /**
   * Ex.: Mon–Fri, 8 a.m.–5 p.m. ET
   */
  hours?: string | null;
  company?: string | null;
  /**
   * Uma linha por quebra.
   */
  address?: string | null;
  /**
   * Link completo do perfil americano. Rede sem link não aparece no site.
   */
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
    x?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destaques_select".
 */
export interface DestaquesSelect<T extends boolean = true> {
  aminosan?:
    | T
    | {
        descricao?: T;
        beneficios?:
          | T
          | {
              icone?: T;
              titulo?: T;
              apoio?: T;
              id?: T;
            };
      };
  produtos?:
    | T
    | {
        produto?: T;
        titulo?: T;
        descricao?: T;
        beneficios?:
          | T
          | {
              icone?: T;
              titulo?: T;
              apoio?: T;
              id?: T;
            };
        corFundo?: T;
        corDestaque?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  whatsapp?: T;
  telefone?: T;
  email?: T;
  emailCompras?: T;
  emailRH?: T;
  horario?: T;
  enderecoBR?:
    | T
    | {
        empresa?: T;
        linhas?: T;
      };
  enderecoUS?:
    | T
    | {
        empresa?: T;
        linhas?: T;
      };
  mapa?: T;
  redes?:
    | T
    | {
        instagram?: T;
        tiktok?: T;
        youtube?: T;
        linkedin?: T;
        facebook?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-us_select".
 */
export interface SettingsUsSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  hours?: T;
  company?: T;
  address?: T;
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        linkedin?: T;
        youtube?: T;
        x?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}